### ISSUE TITLE
That GMT Eco-System logo

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/website#141]
Hi developers.  I have 6 weeks in Hawaii before heading off to Norway.  I would like to refresh some GMT coasters and stickers.  I know logo making is hard and I have not seen much activity for pyGMT and GMT.jl (or GMT/MEX) logos.  I will leave you all to figure those out but in the meantime I think I want a GMT eco-system logo that is square and make a nice beer coaster and sticker.  As you can see in the sandbox repo (guru/gmt-eco-system.sh) it looks like this:

![gmt-eco-system](https://user-images.githubusercontent.com/26473567/187002230-d76c3382-a402-4cb9-bc65-406c325c593c.png)

Yes, it recycles the classic but extremely well known GMT logo but also tries to address the following:

1. Be a square shape
2. Make it clear what GMT is
3. Show where to learn more
4. Indicate what OS it supports
5. List all the environments it can be used in
6. Indicate NSF support

Happy to take comments from @GenericMappingTools/core and @GenericMappingTools/pygmt-admin on minor changes but I am not designing a new "GMT" graphics for it.

**Comment by maxrjones** [comment]
Seems like a good idea and looks nice! I have a slight preference for minimizing the number of colors

![gmt-eco-system-1](https://user-images.githubusercontent.com/14077947/187008450-2143ee00-26f7-4b04-bcae-3422cad90000.png)

**Comment by seisman** [comment]
I'd like to reorganize the names of the wrappers in this way. The two wrappers in each row are similar.
```
CMD     XXXXXXX  SHELL
JULIA   XXXXXXX  PYTHON
MATLAB  XXXXXXX  OCTAVE
```

**Comment by PaulWessel** [comment]
> Seems like a good idea and looks nice! I have a slight preference for minimizing the number of colors
> 

Looks good! Would you mind making a PR on that script with your color choices?

**Comment by joa-quim** [comment]
I would prefer "Family" instead of "Ecosystem". (Softwares do not have ecosystems, despite what current fashion says)

**Comment by PaulWessel** [comment]
Well, families are people so not that much better than ecosystem.  I agree family and ecosystem are both applied to things they were originally not meant for.  I think ecosystem sounds a bit more highbrow than family when we talk about software.  But we live in a (waning) democracy so if @maxrjones @seisman @leouieda @weiji14 want to vote be my guest!

**Comment by maxrjones** [comment]
I prefer ecosystem because it is used so frequently in this context that it should be easily understandable

**Comment by WalterHFSmith** [comment]
Ecosystem works for me, and I am good with the other suggested changes.

**Comment by leouieda** [comment]
No preference here. Family sounds a bit strange but ecosystem implies more competition than collaboration, though it is widely used in this context.

**Comment by PaulWessel** [comment]
It is a good point on collaboration.  Can we think of another byline using something like that instead?  We are repeating "GMT" in the current one since it already says GMT via the logo.  If anyone can think of a more "inclusive" phrase for that bold sentence please try.

**Comment by leouieda** [comment]
How about just removing that line? The you could add "multi-platform | multi-language" below the "Data processing..." bit.

**Comment by liamtoney** [comment]
> How about just removing that line? The you could add "multi-platform | multi-language" below the "Data processing..." bit.

I like that. Like:
```
     generic-mapping-tools.org
Data Processing — Plots — Animations
   Multi-platform | Multi-language
```
It's less redundant (it's nice that the URL spells out the acronym, by the way). My other two suggestions are
1. use italic Helvetica for the "Data Processing..." line, instead of introducing another typeface, and
2. give the QR code a transparent background and perhaps make it blue like the other blue text.

**Comment by liamtoney** [comment]
@PaulWessel what is the difference between "CMD" and "SHELL" ?

**Comment by liamtoney** [comment]
Hypocritically (since I advocated for fewer typefaces) here's a version w/ bold Courier for the URL and italic Palatino instead of Times for the GMT functionality lines. (Along w/ the previous updates already implemented.)

![gmt-eco-system](https://user-images.githubusercontent.com/38269494/188323246-4787d167-a423-4215-aa95-f1050e4d02ed.png)

**Comment by PaulWessel** [comment]
> @PaulWessel what is the difference between "CMD" and "SHELL" ?

SHELL means any of the Unix shells while CMD is Windows Command Line (batch, DOS ,etc).

**Comment by PaulWessel** [comment]
OK I agree with your fonts - see PR listed.

**Comment by PaulWessel** [comment]
I have already ordered 1000 stickers of this design.  However, looking at square coasters they are always cut with rounded corners.   Thus, I tried some modifications to make a coaster-friendly version.  I had to shrink the NSF bottom line and move things up a git but otherwise the same.  Let me know what you think:

![gmt-eco-system-rnd](https://user-images.githubusercontent.com/26473567/188566530-6ff88e24-be96-41af-bc9a-904d3356c919.png)

**Comment by liamtoney** [comment]
Looks good to me!

**Comment by PaulWessel** [comment]
Actually, allowing for the correct coaster size it looks more like below.  I am getting NSF approval to spend money on some swag.  Program manager is OK since we did say we would do that in our proposal.  Once budget is approved I will order these coasters.  The plan is to distribute stickers and coasters to the GMT contributors/developers for further distribution as they see fit.
I am also setting aside funds for mugs and T-shirts for use in our developer recruiting - assuming these funds get approved.

![gmt-eco-system-rnd](https://user-images.githubusercontent.com/26473567/188760142-42e42a49-2580-4b75-a7f4-f9b4452ef04a.png)

**Comment by remkos** [comment]
Nice work. Looking forward to distribute some around the office.

**Comment by WalterHFSmith** [comment]
Me too

**Comment by liamtoney** [comment]
Likewise!

**Comment by maxrjones** [comment]
Looks great!

**Comment by PaulWessel** [comment]
Update: NSF has approved rebudgeting to allow for some swag.  Stickers and coasters have been ordered.  
Can GMT developers and collaborators please email me their full shipping address since it will fall to my secretary to split the goods up and redistribute for you to share with your communities.

**Comment by maxrjones** [comment]
Completed by https://github.com/GenericMappingTools/sandbox/pull/11
