### ISSUE TITLE
Add ipv6 address

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/website#147]
This probably is an IT-issue, but still.
It looks like generic-mapping-tools.org does not have an ipv6 address.

(The same goes for the ``GMT_DATA_SERVER=https://oceania.generic-mapping-tools.org``).

No ``AAAA`` (ipv6) , just `A` (ipv4) when doing dns lookups.

**Comment by seisman** [comment]
What are the reasons that you want ipv6 addresses?

generic-mapping-tools.org is hosted on GitHub and it's possible to support ipv6 as per
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site.

The data mirror oceania.generic-mapping-tools.org is hosted on the server at University of Hawaii and it may support ipv6.

**Comment by anbj** [comment]
Just future-proofing. Probably not very critical yet.

**Comment by anbj** [comment]
Let's close.
