### ISSUE TITLE
Design of the GMT front page

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/website#2]
Since we bought the www.generic-mapping-tools.org domain, we want to host there a front page for the project. This repository has the sphinx sources to build that page (still under development). 

These are some of the ideas we've been bouncing around for what this page should contain:
* Serve as a front page for the entire project (core GMT, Python/Julia/Matlab, GMTSAR, etc)
* Documentation for GMT is separated into https://www.generic-mapping-tools.org/gmt/ (already works). We could also setup a subdomain like https://docs.generic-mapping-tools.org
* Front page links to the several child projects.
* Lots of pretty figures 
* Some history of GMT
* Links to talks, videos, etc
* Sponsors
* How to get involved in the project

Right now, the sources here are served at https://www.generic-mapping-tools.org/website/ for testing purposes. I'll move it to https://www.generic-mapping-tools.org when it's done.

Any ideas/suggestions/complaints?

It would also help a lot if anyone could send some nice (high res) GMT figures to put in the front page.

Here are also some sources of inspiration:

* https://nteract.io
* https://simpeg.xyz
* https://jupyter.org
* http://yt-project.org
* https://www.astropy.org
* https://julialang.org

**Comment by leouieda** [comment]
Pinging @GenericMappingTools/core and @GenericMappingTools/gmt-contributors

**Comment by leouieda** [comment]
It would be great to get some published GMT figure so we can include them in the page with a link to the reference (to give a bit more "prestige")

**Comment by KristofKoch** [comment]
Hi @leouieda 

What do you think about an area on the site where some tips and tricks can be shared? 

GMT is very powerful and can be used for almost anything. However at least for me it wasn't always clear how to achieve it. I received generous help by @PaulWessel et al in the old forum. Over the years I observed that new users have questions similar to those that I had back then. Maybe much of this support work can be replaced by such a tips and tricks area?

The documentation is mostly very precise but at least for me (non-native English speaker) the details are not always easy to grasp. An example helps me way more than a man page. The [CookBook](https://www.generic-mapping-tools.org/gmt/latest/GMT_Docs.html#the-generic-mapping-tools) and the [50 examples from the _historical collection_](https://www.generic-mapping-tools.org/gmt/latest/Gallery.html#the-gmt-historical-collection) are a great help here. However the examples are often hard to understand. Why not take this idea and have a section with small, extensively commented examples for all the small things like lines (like asymmetric area borders, etc), plot borders, tick marks, artificial lighting, custom symbols (exists already), maybe even some data manipulation and similar?

As you were asking for published plots: I could chip in one ore more of the aviation related charts we produce (https://www.planningcharts.com; completely automated generation every 12h; GMT-only):

![AT_2_North_Atlantic_WEST](https://user-images.githubusercontent.com/45796239/57383881-dc416700-71af-11e9-95e0-f0bf08f781c4.png)

Will be provided in high res if desired. I think they don't really highlight the capabilities of GMT though.

**Comment by abanbj** [comment]
Totally agree @KristofKoch. Small, friendly script snippets would be great. These are the ones that get people going.

**Comment by joa-quim** [comment]
We actually have an enormous collection under the [test ](https://github.com/GenericMappingTools/gmt/tree/master/test) dir. Their all not all good for this purpose but so many are, and others could just be simplified.

**Comment by joa-quim** [comment]
@leouieda I managed to recover this old [link ](https://www.google.com/search?q=%22generic+mapping+tools%22+site%3Awikimedia.org&tbm=isch#imgrc=_) provided by Florian many years ago. It's still very good.

**Comment by PaulWessel** [comment]
The wiki link is very impressive!  We need to include that in our docs somehow.

**Comment by leouieda** [comment]
Thanks for all the amazing images @KristofKoch and @joa-quim! I'll definitely include those in the front page.

> However the examples are often hard to understand. Why not take this idea and have a section with small, extensively commented examples for all the small things like lines (like asymmetric area borders, etc), plot borders, tick marks, artificial lighting, custom symbols (exists already), maybe even some data manipulation and similar?

To me, this is exactly what a gallery should be (for example, this what [matplotlib does](https://matplotlib.org/gallery/)) and where I'd like to see the GMT gallery go. Personally, I consider myself an expert matplotlib user and I don't think I've ever actually read the manual. Most of what I know I learned from the gallery and function docs. I imagine this is what most people do. You only dig deep when you need to know the details of something. Most times, you just to crunch numbers, make plots, and get on with your life.

I don't think the front page is the right place for it, though. This is decoupled with the source so including scripts here would make it very hard to make sure they are still working and up to date. The best place for this is a gallery in the docs (under the `gmt` repository). 

What I want in the front page is a lot of eye candy to get people interested. Then we can point them to the docs and gallery to see how to actually make these plots.

**Comment by leouieda** [comment]
@GenericMappingTools/core et al, I've finished the design of the new website. Please have a look at https://www.generic-mapping-tools.org/website/ and let me know what you think. There is some temporary text that needs to be filled. I'd appreciate some help with those. Please open PRs to this repo (see the `.rst` files).

**Comment by leouieda** [comment]
The URL is temporary and once the site is done it will be https://www.generic-mapping-tools.org

**Comment by leouieda** [comment]
Once #7 is merged, we should be done with the website. @PaulWessel @joa-quim @seisman please see if there is anything else urgent that needs to be added before we go live. We can always tweak the website later but it would be bad to have missing text, etc.

**Comment by leouieda** [comment]
Alright, please give me the :+1: if we're good to go with the website.

**Comment by PaulWessel** [comment]
Yes, I am looking through and there are a few things I notice:
Under About it mention PostScript plots.  Should we just say plots in anticipation of 6?  Other than that I think it is OK for now.  Thanks for building the site!

**Comment by joa-quim** [comment]
That also caught my eye, but on the other hand we don't want to make the PostScript a secret thing. I'm fine with leaving it as is.

OK

**Comment by seisman** [comment]
A few things which may be improved a little bit:

1. GMT4 or GMT5 users may be confused which paper they should cite, and for other technical papers, at least we should mention the name of the module.

2. The link to the GMTMex documentation is wrong.

**Comment by leouieda** [comment]
> Should we just say plots in anticipation of 6? 

We could say that we make plots using the PostScript language as the rendering engine or something like that.

> GMT4 or GMT5 users may be confused about which paper they should cite

I agree. It would be good to have a note about which paper to cite for which version of GMT.

> technical papers, at least we should mention the name of the module.

That was in the original docs but I must have deleted when copying over. Will restore.

> The link to the GMTMex documentation is wrong.

Thanks!

**Comment by leouieda** [comment]
OK, all but the PostScript mention is fixed.

**Comment by leouieda** [comment]
The page is live! https://www.generic-mapping-tools.org/
