### ISSUE TITLE
Discourse jump-start

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/website#28]
Hi @GenericMappingTools/core-

We have 1646 subscribers on the old Redmine forum.  I think we should write them a one-time email via bcc that says something like this:

> Dear GMT Forum subscriber-
> 
> We wish to notify you via this one-time email that the old forum hosted at gmt.soest.hawaii.edu will soon go offline.  We encourage you instead to register at our new user forum
> 
> forum.generic-mapping-tools.org
> 
> The link is also available form our main website www.generic-mapping-tools.org where you also find links to GMT releases, documentation, news, our GitHub repository and issue trackers for reporting bugs or requesting new features.
> 
> Thanks for being a GMT user.
> 
> The GMT Team

I have the list of emails, is there a good way to do this via command line mail?

**Comment by leouieda** [comment]
Yep, that sounds like a really good idea.

**Comment by remkos** [comment]
I see you already corrected discourse->forum from the original.
I just signed up with my GitHub account, and it worked nicely.
So you're good to go with this.
