### ISSUE TITLE
Rearrange items on website

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/website#55]
Currently the website is not very inviting or informative at a first glance. The content is there but not immediately visible. I propose to rearrange the items for a better appeal for new users. See my [forum post](https://forum.generic-mapping-tools.org/t/improve-website-appeal/472) for context.

current version:
![eb71c470bc3e68b67813b8398014616d6375c2be_2_1380x876](https://user-images.githubusercontent.com/45796239/82113634-d7ff4080-9757-11ea-8d3d-97146d29f62e.jpeg)

proposed version:
![f870076f1532fd6e4bee2ac082d9e0c3030f79f0_2_1380x876](https://user-images.githubusercontent.com/45796239/82113640-e0577b80-9757-11ea-82d4-8c09f54824cd.jpeg)

If this idea is accepted by the  @GenericMappingTools/core devs I'd go ahead and make the appropriate changes.

(Opened here again as I mistakenly opened it in /gmt)

**Comment by leouieda** [comment]
Hi @KristofKoch I like this idea. We could move the current News/Releases etc to the bottom of the page. Not sure how others feel about this, though.

**Comment by PaulWessel** [comment]
I think that makes sense. It should be somewhat clear what the GMT page is about and moving that up spells it out right away.

**Comment by KristofKoch** [comment]
I took the liberty to rephrase the first two paragraphs a bit a s well. 

> A toolbox for Earth, Ocean, and Planetary Science
> 
> The Generic Mapping Tools (GMT) are widely used across the Earth, Ocean, and Planetary sciences and beyond. A diverse community uses GMT to process data, generate publication-quality illustrations, automate workflows, and make animations. Scientific journals, posters at meetings, Wikipedia pages, and many more publications display illustrations made by GMT. And the best part: it is free, open source software licensed under the LGPL.
> 
> Got questions? Head over to the friendly GMT Community Forum to get help and connect with other users and developers.

I felt that the information about GMT being OSS is not the main selling point but more of an added bonus. I hope you don't mind.
