### ISSUE TITLE
Links to GSHHG and DCW

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/website#61]
I think the links to *Support Data* (i.e. GSHHG and DCW, https://www.generic-mapping-tools.org/download/) should be changed from a filename containing version information to just  gshhg-gmt.tar.gz and dcw-gmt.tar.gz. Then create symlinks behind the curtain to the actual tarballs. This way you dont have to change the address in scripts etc. every time there is a new release.

**Comment by leouieda** [comment]
@anbj thanks for the suggestion! That's not a bad idea. Though the released of these two data sets are so infrequent that it might not be worth the time. But for the GMT release, we might want to link to https://github.com/GenericMappingTools/gmt/releases/latest (but again, the releases are infrequent enough not to make a big difference).

**Comment by anbj** [comment]
Hi @leouieda!

Yes, I see your point. Had to share the idea. Closing!
