### ISSUE TITLE
Give hosts more credit

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/website#78]
I think for the data mirrors we need to acknowledge the hosting institutions since they otherwise are left completely out.  Probably should add a general statement under the Data mirror site to say "We thank the hosting institutions for mirroring the GMT data distribution so that users can have a faster download wherever they are located."  Then for each data mirror we need to list the organization.  For oceania that is SOEST, U of Hawaii, but I an not sure if there is a distinction between master and mirror since we are not a mirror but the original source.

**Comment by seisman** [comment]
> I think for the data mirrors we need to acknowledge the hosting institutions since they otherwise are left completely out.

Yes, I fully agree.

> if there is a distinction between master and mirror since we are not a mirror but the original source.

We can add a note that the Hawaii site is the master host.
