### ISSUE TITLE
All mirrors are offline

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/website#92]
![image](https://user-images.githubusercontent.com/3974108/100962269-02e19400-34f2-11eb-9955-9646d03bdd71.png)

all mirrors are saying:

![image](https://user-images.githubusercontent.com/3974108/100962296-0ecd5600-34f2-11eb-9b66-7966dc046420.png)

Something wrong with the domain settings?

**Comment by PaulWessel** [comment]
Strange, but nothing has changed here.  I have asked Hover (our forwarding service).

**Comment by seisman** [comment]
They are all green now.
