### ISSUE TITLE
Add twitter link to website

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/website#99]
Now that we have a twitter handle at https://twitter.com/gmt_dev as announced at https://forum.generic-mapping-tools.org/t/gmt-is-on-twitter/1461 (thanks @meghanrjones!), how about adding it to the website. I think we can do two things:

1. Add a Twitter :bird: icon next to the Github/Youtube icons on the top right corner
2. Add a news announcement that we have a Twitter account!

Happy to add this in myself (unless someone else wants to have a go).

**Comment by meghanrjones** [comment]
Great idea!

**Comment by weiji14** [comment]
Cool, I think I'll just make a PR for it, give me a few minutes :smile:
